### ISSUE TITLE
User feedback loop

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/reentry-resources-hub#74]
This is more a thinking/planning exercise. We will have a contact form that site users can use to report errors or give feedback. How can we go beyond this through some combination of standard web analytics, custom analytics built into the site, and different forms of direct engagement with site users to get ongoing feedback to improve the site.

**Comment by JungleJim2** [comment]
What a great idea :-) There may be a several types of users from which we might benefit from their feedback: (1) people in government and services that recommend the site, (2) the people who use the site because they are returning to our community from incarceration, and (3) other people who recommend the site (family/friends/community members?).

**Comment by ejaxon** [comment]
Closing this for now - trying to clean up the project as we move toward initial release. We'll create new issues where relevant, but may be in a different repo.
