### ISSUE TITLE
Review County Modal Design

### ISSUE THREAD

**Issue by marshallj** [CodeForNC/reentry-resources-hub#76]
Determine if a better design should be implemented for the County Modal that is displayed with links to the 100 NC Counties. Account for desktop/laptop/mobile screen sizes. 

Please propose any design suggestions before beginning work to implement.

**Comment by Sadaajit** [comment]
Was playing around with this issue. When I try to make changes to the font size all that happens is that the space between the counties increases, the font itself does not increase. It seems to me that CSS needs to be applied to the list of counties, however, I'm not sure how that can be done.

Also, it might be nice to have a slightly different style of modal, that has a rolling scroll mechanism, instead of the entire list scrolling. I think this would work better on mobile devices, as well. I can look into this if you think it's a good idea.

**Comment by ejaxon** [comment]
Not sure what the issue is, @Sadaajit, but we may want to consider a more extensive redesign of navigation between counties. Check out the discussion over in [issue 71](https://github.com/CodeForNC/reentry-resources-hub/issues/71). cc: @marshallj

**Comment by marshallj** [comment]
@Sadaajit you can include a className attribute on the Button tag in CountyModal.jsx like so:

```html
<Button className="buttonText" bsStyle="link" href={`/${county}/home`}>
```
Then use the className as a class in the css.

**Comment by Sadaajit** [comment]
I think I tried this, but will try it just in case I put it someplace else. Will be working on this tomorrow.

Sadaajit

**Comment by jandrewwhit** [comment]
@Sadaajit Don't worry about it. I figured out the modal design. I now have the modal with a larger font for the counties and a vertical scroll in my local version. I just need some opinions on it and I guess push it back to the master branch.

**Comment by marshallj** [comment]
@jandrewwhit and @Sadaajit, @matthannam implemented a search filter for the modal. It's pretty slick. Pull it down from master and take a look. We may still need to redesign the 'Select County' experience as @ejaxon mentioned in the comment above, but this will involve some discussion/planning. I wouldn't recommend doing too much else with this one until further notice, unless you just want to experiment.

**Comment by marshallj** [comment]
Closing for now. Will likely create additional issues related to this in the future as feature discussions mature.
