### ISSUE TITLE
Review Build/Release workflow and stand up Jenkins Server

### ISSUE THREAD

**Issue by giancarlopetrini** [CodeForNC/reentry-resources-hub#83]
## This is a: 

* [ ] bug
* [ ] enhancement
* [x ] feature-discussion

 

# Feature-Discussion

Leverage Jenkins for automated build, unit tests, and push releases with integration through GitHub and AWS. Will require separate AWS instance running Jenkins with necessary IAM roles to access production or staging EC2's

**Comment by ejaxon** [comment]
So I'll start by admitting that I've never actually done this, so I probably am operating from a bias against. That said, I want to make sure I understand the value/cost.

First, on the cost side, there are two. One is the cost of the Jenkins instance on AWS - not a big deal, but given $0 revenue for the company operating it ... :). The bigger cost is just the additional complexity that anyone maintaining the system has to understand. I don't have a sense how much that's actually a factor.

On the value side, as long as everything works, I can see that it would be nice to avoid the usual process of logging in and manually doing the pulls and service restarts, especially since I personally do not seem to be able to do that without making at least 7 stupid mistakes.

In terms of complexity of what's being built/tested/released, we have 4 pieces, only 3 of which would operate through this:

1. [Public site](https://github.com/CodeForNC/reentry-resources-hub) - definitely relevant here
2. [Admin API](https://github.com/CodeForNC/reentry-admin-api) - relevant here as well - this must run on the same server as the public site since it maintains the files that it uses
3. [Admin UI](https://github.com/CodeForNC/reentry-admin-ui) - This can and probably should be run serverless since it's basically just an html page and script bundle - it gets all the data by talking to the API.
4. [Content](https://github.com/CodeForNC/nc-reentry-resources-content) - this will live on the same server as (1) and (2), but contains no code and has a workflow going in the opposite direction since changes here will be pushed from the server into the repo

@giancarlopetrini I'd like to get your sense of the level of effort/complexity to create & maintain the automation system for 1 & 2 (could do 3 as well, though it will publish to a different AWS service).

**Comment by giancarlopetrini** [comment]
Thanks for the quick response. We should be able to write a pretty clear SOP to accompany a CI implementation for any that would need to maintain the system going forward. I'll begin setting up a barebones implementation so that I can better address your questions; I've never done this either!!

If anything, it will be a good learning process for me. I have worked extensively with AWS/automated deployments so that should speed up the fact finding process.

**Comment by ejaxon** [comment]
Perfect!

**Comment by ejaxon** [comment]
I'm going to close this for now since we probably need to rethink deployment. Watch the repo for new issues as we get reorganized to (finally) launch.
